### ISSUE TITLE
Does this plugin work with Sanity V3?

### ISSUE THREAD

**Issue by morgnism** [hdoro/sanity-plugin-asset-source-ogimage#21]
The [Sanity plugins site](https://www.sanity.io/plugins/asset-source-ogimage) has a warning that this plugin only works in V2, but given your Youtube video and config, will this work in Sanity V3?

If not, is it possible for me to be added as a collaborator so that I can add a version for V3?

**Comment by jschuur** [comment]
> The [Sanity plugins site](https://www.sanity.io/plugins/asset-source-ogimage) has a warning that this plugin only works in V2, but given your Youtube video and config, will this work in Sanity V3?
> 
> If not, is it possible for me to be added as a collaborator so that I can add a version for V3?

I came wondering the same thing. @morgnism you could fork it and update it to v3 and send a PR in the mean time.

**Comment by morgnism** [comment]
> I came wondering the same thing. @morgnism you could fork it and update it to v3 and send a PR in the mean time.

Great idea and my thoughts exactly. I wasn't sure if maybe they had something in the works because Henrique has a few useful plugins that haven't been updated yet.

Here's my [forked repo](https://github.com/morgnism/sanity-plugin-asset-source-ogimage) if you're interested in helping upgrade this repo too.

**Comment by morgnism** [comment]
Update: apparently there's a `sanity-v3` branch that's been in the works. This earlier [issue](https://github.com/hdoro/sanity-plugin-asset-source-ogimage/issues/19) started by @hdoro makes sense now.

I'm closing this issue because the new package is close to complete. Seems like it just needs a better handler for SVG to image conversions.
